# Generated by Django 5.2.12 on 2026-03-29 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counter1Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(default='Authorized Pass', max_length=100)),
                ('user_photo', models.TextField(blank=True, null=True)),
                ('ticket_type', models.CharField(default='General', max_length=50)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('calling', 'Calling'), ('served', 'Served')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_counter_num', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Counter 1 Ticket',
                'verbose_name_plural': 'Counter 1 Tickets',
            },
        ),
        migrations.CreateModel(
            name='Counter2Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(default='Authorized Pass', max_length=100)),
                ('user_photo', models.TextField(blank=True, null=True)),
                ('ticket_type', models.CharField(default='General', max_length=50)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('calling', 'Calling'), ('served', 'Served')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_counter_num', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Counter 2 Ticket',
                'verbose_name_plural': 'Counter 2 Tickets',
            },
        ),
        migrations.CreateModel(
            name='Counter3Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(default='Authorized Pass', max_length=100)),
                ('user_photo', models.TextField(blank=True, null=True)),
                ('ticket_type', models.CharField(default='General', max_length=50)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('calling', 'Calling'), ('served', 'Served')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_counter_num', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Counter 3 Ticket',
                'verbose_name_plural': 'Counter 3 Tickets',
            },
        ),
        migrations.CreateModel(
            name='CrowdRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('face_count', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoutingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=15)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assigned_counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.counter')),
            ],
        ),
    ]
